### ISSUE TITLE
jinja2_humanize_extension is missing from requirements

### ISSUE THREAD

**Issue by kavvkon** [conda-forge/prefect-feedstock#301]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

`jinja2_humanize_extension` doesn't exist in recipe. In fact it does not exist in conda-forge and needs to be installed from pip.
Therefore prefect (e.g. flow() decorator) doesnt work if installed only from conda-forge

```python
Traceback (most recent call last):
  File "d:\Projects\subs\src\parse_demand.py", line 26, in <module>
    download_all_files()
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\flows.py", line 1228, in __call__
    return enter_flow_run_engine_from_flow_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\engine.py", line 291, in enter_flow_run_engine_from_flow_call
    retval = from_sync.wait_for_call_in_loop_thread(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\_internal\concurrency\api.py", line 218, in wait_for_call_in_loop_thread
    return call.result()
           ^^^^^^^^^^^^^
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 318, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 179, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 389, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\client\utilities.py", line 69, in with_injected_client
    client, inferred = get_or_create_client(client)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\client\utilities.py", line 52, in get_or_create_client
    return get_httpx_client(), False
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\client\orchestration.py", line 183, in get_client
    from prefect.server.api.server import create_app
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\server\__init__.py", line 1, in <module>
    from . import models, orchestration, schemas, services
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\server\models\__init__.py", line 1, in <module>
    from . import (
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\server\models\agents.py", line 13, in <module>
    from prefect.server.database.dependencies import inject_db
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\server\database\dependencies.py", line 17, in <module>
    from prefect.server.database.interface import PrefectDBInterface
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\server\database\interface.py", line 9, in <module>
    from prefect.server.database.orm_models import BaseORMConfiguration
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\server\database\orm_models.py", line 22, in <module>
    from prefect.server.events.actions import ActionTypes
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\server\events\actions.py", line 79, in <module>
    from prefect.server.utilities.user_templates import (
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\server\utilities\user_templates.py", line 19, in <module>
    _template_environment = ImmutableSandboxedEnvironment(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\jinja2\sandbox.py", line 253, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\jinja2\environment.py", line 363, in __init__
    self.extensions = load_extensions(self, extensions)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\jinja2\environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kavvkon\Anaconda3\envs\prefectenv\Lib\site-packages\jinja2\utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'jinja2_humanize_extension'
```

### Installed packages

```shell
# packages in environment at C:\Users\kavvkon\Anaconda3\envs\prefectenv:
#
# Name                    Version                   Build  Channel
aiohttp                   3.9.5           py311ha68e1ae_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
aiosqlite                 0.19.0             pyhd8ed1ab_0    conda-forge
alembic                   1.13.1             pyhd8ed1ab_1    conda-forge
annotated-types           0.6.0              pyhd8ed1ab_0    conda-forge
anyio                     3.7.1              pyhd8ed1ab_0    conda-forge
apprise                   1.7.6              pyhd8ed1ab_0    conda-forge
asgi-lifespan             2.1.0              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-exit-stack          1.0.1              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.3              pyhd8ed1ab_0    conda-forge
asyncpg                   0.29.0          py311ha68e1ae_0    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
bcrypt                    4.1.2           py311hc37eb10_0    conda-forge
blinker                   1.7.0              pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0           py311h12c1d0e_1    conda-forge
bzip2                     1.0.8                hcfcfb64_5    conda-forge
ca-certificates           2024.2.2             h56e8100_0    conda-forge
cachetools                5.3.3              pyhd8ed1ab_0    conda-forge
cairo                     1.18.0               h1fef639_0    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py311ha68e1ae_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           win_pyh7428d3b_0    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
coolname                  2.2.0              pyhd8ed1ab_0    conda-forge
croniter                  1.4.1              pyhd8ed1ab_0    conda-forge
cryptography              42.0.5          py311h28e9c30_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
dateparser                1.2.0              pyhd8ed1ab_0    conda-forge
docker-py                 6.1.3              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
expat                     2.6.2                h63175ca_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
fribidi                   1.0.10               h8d14728_0    conda-forge
frozenlist                1.4.1           py311ha68e1ae_0    conda-forge
fsspec                    2024.3.1           pyhca7485f_0    conda-forge
getopt-win32              0.1                  hcfcfb64_1    conda-forge
google-auth               2.29.0             pyhca7485f_0    conda-forge
graphite2                 1.3.13            h63175ca_1003    conda-forge
graphviz                  9.0.0                h51cb2cd_1    conda-forge
greenlet                  3.0.3           py311h12c1d0e_0    conda-forge
griffe                    0.44.0             pyhd8ed1ab_0    conda-forge
gts                       0.7.6                h6b5321d_4    conda-forge
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
harfbuzz                  8.4.0                h7ab893a_0    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  1.0.5              pyhd8ed1ab_0    conda-forge
httpx                     0.27.0             pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       73.2                 h63175ca_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
importlib-metadata        7.1.0              pyha770c72_0    conda-forge
importlib_metadata        7.1.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
intel-openmp              2024.1.0           h57928b3_965    conda-forge
jinja2                    3.1.3              pyhd8ed1ab_0    conda-forge
jsonpatch                 1.33               pyhd8ed1ab_0    conda-forge
jsonpointer               2.4             py311h1ea47a8_3    conda-forge
jsonschema                4.21.1             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              22_win64_mkl    conda-forge
libcblas                  3.9.0              22_win64_mkl    conda-forge
libdeflate                1.20                 hcfcfb64_0    conda-forge
libexpat                  2.6.2                h63175ca_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libgd                     2.3.3                h312136b_9    conda-forge
libglib                   2.80.0               h39d0aa6_6    conda-forge
libhwloc                  2.10.0          default_h2fffb23_1000    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libintl                   0.22.5               h5728263_2    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
liblapack                 3.9.0              22_win64_mkl    conda-forge
libpng                    1.6.43               h19919ed_0    conda-forge
libsqlite                 3.45.3               hcfcfb64_0    conda-forge
libtiff                   4.6.0                hddb2be6_3    conda-forge
libwebp                   1.3.2                hcfcfb64_1    conda-forge
libwebp-base              1.3.2                hcfcfb64_1    conda-forge
libxcb                    1.15                 hcd874cb_0    conda-forge
libxml2                   2.12.6               hc3477c8_2    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mako                      1.3.3              pyhd8ed1ab_0    conda-forge
markdown                  3.6                pyhd8ed1ab_0    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.5           py311ha68e1ae_0    conda-forge
mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
mkl                       2024.1.0           h66d3029_692    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multidict                 6.0.5           py311ha68e1ae_0    conda-forge
numpy                     1.26.4          py311h0b4df5a_0    conda-forge
oauthlib                  3.2.2              pyhd8ed1ab_0    conda-forge
openssl                   3.2.1                hcfcfb64_1    conda-forge
orjson                    3.10.1          py311h633b200_0    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2           py311hf63dbb6_0    conda-forge
pango                     1.52.2               h07c897b_0    conda-forge
paramiko                  3.4.0              pyhd8ed1ab_0    conda-forge
pathspec                  0.12.1             pyhd8ed1ab_0    conda-forge
pcre2                     10.43                h17e33f8_0    conda-forge
pendulum                  2.1.2           py311ha68e1ae_6    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pixman                    0.43.4               h63175ca_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
prefect                   2.18.0             pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pyasn1                    0.6.0              pyhd8ed1ab_0    conda-forge
pyasn1-modules            0.4.0              pyhd8ed1ab_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pydantic                  2.7.1              pyhd8ed1ab_0    conda-forge
pydantic-core             2.18.2          py311h533ab2d_0    conda-forge
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pyjwt                     2.8.0              pyhd8ed1ab_1    conda-forge
pynacl                    1.5.0           py311hd53affc_3    conda-forge
pyopenssl                 24.0.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.11.9          h631f459_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-graphviz           0.20.3             pyh717bed2_0    conda-forge
python-kubernetes         28.1.0             pyhd8ed1ab_0    conda-forge
python-slugify            8.0.4              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytz                      2023.4             pyhd8ed1ab_0    conda-forge
pytzdata                  2020.1             pyh9f0ad1d_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pywin32                   306             py311h12c1d0e_2    conda-forge
pywin32-on-windows        0.1.0              pyh07e9846_2    conda-forge
pyyaml                    6.0.1           py311ha68e1ae_1    conda-forge
readchar                  4.0.5              pyhd8ed1ab_0    conda-forge
referencing               0.34.0             pyhd8ed1ab_0    conda-forge
regex                     2024.4.16       py311ha68e1ae_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
requests-oauthlib         2.0.0              pyhd8ed1ab_0    conda-forge
rich                      13.7.1             pyhd8ed1ab_0    conda-forge
rpds-py                   0.18.0          py311hc37eb10_0    conda-forge
rsa                       4.9                pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.18.6          py311ha68e1ae_0    conda-forge
ruamel.yaml.clib          0.2.8           py311ha68e1ae_0    conda-forge
setuptools                69.5.1             pyhd8ed1ab_0    conda-forge
shellingham               1.5.4              pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
sqlalchemy                2.0.29          py311ha68e1ae_0    conda-forge
starlette                 0.27.0             pyhd8ed1ab_0    conda-forge
tbb                       2021.12.0            h91493d7_0    conda-forge
text-unidecode            1.3                pyhd8ed1ab_1    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
typer                     0.12.3             pyhd8ed1ab_0    conda-forge
typer-slim                0.12.3             pyhd8ed1ab_0    conda-forge
typer-slim-standard       0.12.3               hd8ed1ab_0    conda-forge
typing-extensions         4.11.0               hd8ed1ab_0    conda-forge
typing_extensions         4.11.0             pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
tzlocal                   5.2             py311h1ea47a8_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
ujson                     5.9.0           py311h12c1d0e_0    conda-forge
urllib3                   1.26.18            pyhd8ed1ab_0    conda-forge
uvicorn                   0.29.0          py311h1ea47a8_0    conda-forge
vc                        14.3                hcf57466_18    conda-forge
vc14_runtime              14.38.33130         h82b7239_18    conda-forge
vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
websocket-client          1.8.0              pyhd8ed1ab_0    conda-forge
websockets                11.0.3          py311ha68e1ae_1    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
xorg-kbproto              1.0.7             hcd874cb_1002    conda-forge
xorg-libice               1.1.1                hcd874cb_0    conda-forge
xorg-libsm                1.2.4                hcd874cb_0    conda-forge
xorg-libx11               1.8.9                hefa74cf_0    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xorg-libxext              1.3.4                hcd874cb_2    conda-forge
xorg-libxpm               3.5.17               hcd874cb_0    conda-forge
xorg-libxt                1.3.0                hcd874cb_1    conda-forge
xorg-xextproto            7.3.0             hcd874cb_1003    conda-forge
xorg-xproto               7.0.31            hcd874cb_1007    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yarl                      1.9.4           py311ha68e1ae_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hcfcfb64_5    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge
```

### Environment info

```shell
active environment : prefectenv
    active env location : C:\Users\kavvkon\Anaconda3\envs\prefectenv
            shell level : 1
       user config file : C:\Users\kavvkon\.condarc
 populated config files : C:\Users\kavvkon\.condarc
          conda version : 23.11.0
    conda-build version : 3.28.2
         python version : 3.8.18.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=x86_64
                          __conda=23.11.0=0
                          __win=0=0
       base environment : C:\Users\kavvkon\Anaconda3  (writable)
      conda av data dir : C:\Users\kavvkon\Anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\kavvkon\Anaconda3\pkgs
                          C:\Users\kavvkon\.conda\pkgs
                          C:\Users\kavvkon\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\kavvkon\Anaconda3\envs
                          C:\Users\kavvkon\.conda\envs
                          C:\Users\kavvkon\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.8.18 Windows/10 Windows/10.0.19045 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.6
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by peterbygrave** [comment]
PR to add jinja2-humanize-extension to conda forge https://github.com/conda-forge/staged-recipes/pull/26151
